<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <?php 

        $timezoneIdentifier = getenv('TIMEZONE_IDENTIFIER');

        date_default_timezone_set($timezoneIdentifier); 

        $dateTimeZone = new DateTimeZone($timezoneIdentifier);
        $dateTime = new DateTime("now", $dateTimeZone);

        $time = time();
        $lat = (float)getenv('LATITUDE');
        $long = (float)getenv('LONGTITUDE');
        $offset = round(abs($dateTimeZone->getOffset($dateTime)) / 3600);
        $zenith= 90 + 50/60;

        $sunrise = date_sunrise($time, SUNFUNCS_RET_TIMESTAMP, $lat, $long, $zenith, $offset);
        $sunset = date_sunset($time, SUNFUNCS_RET_TIMESTAMP, $lat, $long, $zenith, $offset);
        $median = ($sunrise + $sunset) / 2;

        $mainCssClassName = '';

        if($time > $sunrise && $time < $median){
            $mainCssClassName = 'summer-sky';
        }elseif($time > $median && $time < $sunset){
            $mainCssClassName = 'sunset';
        }else{
            $mainCssClassName = 'late-sunset';
        }

    ?>

        <div class="wrap <?php echo $mainCssClassName; ?>">
<!--             <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <?php if(!$this->zfcUserIdentity()): ?>
                                <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
                        <?php else: ?>
                                <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                        <?php endif?>
                    </div>
                </div>
            </nav> -->
            <div class="container">
                <br/><br/>
                <br/><br/>
                <?php echo $this->content; ?>
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
