<div class="panel panel-default">
	<div class="panel-heading">
	    <h3 class="panel-title"><?php echo $this->translate('Location Details') ?></h3>
	</div>
	<div class="panel-body">
		<ul class="list-group">
			<?php foreach ($this->locationDetails as $key => $value): ?>
    		<li class="list-group-item"><?php echo $key; ?>: <?php echo $value; ?></li>
    	<?php endforeach; ?>
		</ul>
	</div>
</div>