
<div class="row">
	<div class="col-md-8">
		<div class="jumbotron">
			<h1>
				<?= sprintf($this->translate('%sMy Weather Station%s'), '<span class="zf-green">', '</span>'); ?>
			</h1>
			<p><?php echo $this->translate('Welcome to my weather station!'); ?></p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default" style="background-color: #eee">
			<div class="panel-body">
				<div class="jumb-weather-icon">
					<div class="sunny-icon"></div>
				</div>
				<span>17oC</span>
			</div>
		</div>
	</div>
</div>